<h1><span dir="auto">Lorem ipsum</span></h1>

<div id="bodyContent" style="font-size: 0.8em; position: relative; width: 1678px; line-height: 1.5em; color: rgb(0, 0, 0); font-family: sans-serif;">
<div id="contentSub" style="font-size: 11px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(125, 125, 125); width: auto;">&nbsp;</div>

<div class="mw-jump" id="jump-to-nav" style="overflow: hidden; height: 0px; zoom: 1; margin-top: -1.4em; margin-bottom: 1.4em;">&nbsp;</div>

<div class="mw-content-ltr" dir="ltr" id="mw-content-text" lang="es" style="direction: ltr;">
<div class="thumb tright" style="clear: right; float: right; margin: 0.5em 0px 1.3em 1.4em; width: auto; background-color: transparent;">
<div class="thumbinner" style="border: 1px solid rgb(204, 204, 204); background-color: rgb(249, 249, 249); font-size: 12px; text-align: center; overflow: hidden; padding: 3px !important; width: 202px;"><a class="image" href="http://commons.wikimedia.org/wiki/File:Lorem_ipsum_design.svg" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;"><img alt="" class="thumbimage" src="http://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Lorem_ipsum_design.svg/200px-Lorem_ipsum_design.svg.png" style="border:1px solid rgb(204, 204, 204); height:225px; vertical-align:middle; width:200px" /></a>

<div class="thumbcaption" style="border: none; line-height: 1.4em; font-size: 11px; padding: 3px !important; text-align: left;">
<div class="magnify" style="margin-left: 3px; border: none !important; background-image: none !important; float: right; background-position: initial initial !important; background-repeat: initial initial !important;"><a class="internal" href="http://es.wikipedia.org/wiki/Archivo:Lorem_ipsum_design.svg" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none !important; display: block; border: none !important; background-position: initial initial !important; background-repeat: initial initial !important;" title="Aumentar"><img alt="" src="http://bits.wikimedia.org/static-1.22wmf18/skins/common/images/magnify-clip.png" style="background-image:none !important; background-position:initial initial !important; background-repeat:initial initial !important; border:none !important; display:block; height:11px; vertical-align:middle; width:15px" /></a></div>
Ejemplo de Lorem ipsum.</div>
</div>
</div>

<p><strong>Lorem ipsum</strong>&nbsp;es el texto que se usa habitualmente en&nbsp;<a href="http://es.wikipedia.org/wiki/Dise%C3%B1o_gr%C3%A1fico" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Diseño gráfico">dise&ntilde;o gr&aacute;fico</a>&nbsp;en demostraciones de&nbsp;<a href="http://es.wikipedia.org/wiki/Tipograf%C3%ADa" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Tipografía">tipograf&iacute;as</a>&nbsp;o de&nbsp;<a class="mw-redirect" href="http://es.wikipedia.org/wiki/Borrador_(boceto)" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Borrador (boceto)">borradores</a>&nbsp;de dise&ntilde;o para probar el dise&ntilde;o visual antes de insertar el texto final.</p>

<p>Aunque no posee actualmente fuentes para justificar sus hip&oacute;tesis, el profesor de filolog&iacute;a cl&aacute;sica Richard McClintock asegura que su uso se remonta a los impresores de comienzos del siglo XVI.<sup><a href="http://es.wikipedia.org/wiki/Lorem_ipsum#cite_note-1" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; white-space: nowrap; background-position: initial initial; background-repeat: initial initial;">1</a></sup>&nbsp;Su uso en algunos&nbsp;<a href="http://es.wikipedia.org/wiki/Editor_de_texto" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editor de texto">editores de texto</a>&nbsp;muy conocidos en la actualidad ha dado al texto&nbsp;<em>lorem ipsum</em>&nbsp;nueva popularidad.</p>

<p>El texto en s&iacute; no tiene sentido, aunque no es completamente aleatorio, sino que deriva de un texto de&nbsp;<a class="mw-redirect" href="http://es.wikipedia.org/wiki/Cicer%C3%B3n" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Cicerón">Cicer&oacute;n</a>&nbsp;en lengua&nbsp;<a href="http://es.wikipedia.org/wiki/Lat%C3%ADn" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Latín">latina</a>, a cuyas palabras se les han eliminado s&iacute;labas o letras. El significado del texto no tiene importancia, ya que s&oacute;lo es una demostraci&oacute;n o prueba, sino que copia de la obra de&nbsp;<a class="mw-redirect" href="http://es.wikipedia.org/wiki/Cicer%C3%B3n" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Cicerón">Cicer&oacute;n</a>&nbsp;<em>De finibus bonorum et malorum</em>&nbsp;(<em>Sobre los l&iacute;mites del bien y del mal</em>) que comienza con:</p>

<blockquote>
<p>Neque porro quisquam est qui do<strong>lorem ipsum</strong>&nbsp;quia&nbsp;<strong>dolor sit amet, consectetur, adipisci</strong>&nbsp;v<strong>elit</strong><sup><a href="http://es.wikipedia.org/wiki/Lorem_ipsum#cite_note-2" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; white-space: nowrap; background-position: initial initial; background-repeat: initial initial;">2</a></sup></p>
</blockquote>

<p>A pesar de estar extra&iacute;do de ese escrito, el texto usado habitualmente es:</p>

<blockquote>
<p>Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos. Eu sit tincidunt incorrupte definitionem, vis mutat affert percipit cu, eirmod consectetuer signiferumque eu per. In usu latine equidem dolores. Quo no falli viris intellegam, ut fugit veritus placerat per.</p>

<p>Ius id vidit volumus mandamus, vide veritus democritum te nec, ei eos debet libris consulatu. No mei ferri graeco dicunt, ad cum veri accommodare. Sed at malis omnesque delicata, usu et iusto zzril meliore. Dicunt maiorum eloquentiam cum cu, sit summo dolor essent te. Ne quodsi nusquam legendos has, ea dicit voluptua eloquentiam pro, ad sit quas qualisque. Eos vocibus deserunt quaestio ei.</p>

<p>Blandit incorrupte quaerendum in quo, nibh impedit id vis, vel no nullam semper audiam. Ei populo graeci consulatu mei, has ea stet modus phaedrum. Inani oblique ne has, duo et veritus detraxit. Tota ludus oratio ea mel, offendit persequeris ei vim. Eos dicat oratio partem ut, id cum ignota senserit intellegat. Sit inani ubique graecis ad, quando graecis liberavisse et cum, dicit option eruditi at duo. Homero salutatus suscipiantur eum id, tamquam voluptaria expetendis ad sed, nobis feugiat similique usu ex.</p>

<p>Eum hinc argumentum te, no sit percipit adversarium, ne qui feugiat persecuti. Odio omnes scripserit ad est, ut vidit lorem maiestatis his, putent mandamus gloriatur ne pro. Oratio iriure rationibus ne his, ad est corrumpit splendide. Ad duo appareat moderatius, ei falli tollit denique eos. Dicant evertitur mei in, ne his deserunt perpetua sententiae, ea sea omnes similique vituperatoribus. Ex mel errem intellegebat comprehensam, vel ad tantas antiopam delicatissimi, tota ferri affert eu nec. Legere expetenda pertinacia ne pro, et pro impetus persius assueverit.</p>

<p>Ea mei nullam facete, omnis oratio offendit ius cu. Doming takimata repudiandae usu an, mei dicant takimata id, pri eleifend inimicus euripidis at. His vero singulis ea, quem euripidis abhorreant mei ut, et populo iriure vix. Usu ludus affert voluptaria ei, vix ea error definitiones, movet fastidii signiferumque in qui.</p>

<p>Vis prodesset adolescens adipiscing te, usu mazim perfecto recteque at, assum putant erroribus mea in. Vel facete imperdiet id, cum an libris luptatum perfecto, vel fabellas inciderint ut. Veri facete debitis ea vis, ut eos oratio erroribus. Sint facete perfecto no vel, vim id omnium insolens. Vel dolores perfecto pertinacia ut, te mel meis ullum dicam, eos assum facilis corpora in.</p>

<p>Mea te unum viderer dolores, nostrum detracto nec in, vis no partem definiebas constituam. Dicant utinam philosophia has cu, hendrerit prodesset at nam, eos an bonorum dissentiet. Has ad placerat intellegam consectetuer, no adipisci mandamus senserit pro, torquatos similique percipitur est ex. Pro ex putant deleniti repudiare, vel an aperiam sensibus suavitate. Ad vel epicurei convenire, ea soluta aliquid deserunt ius, pri in errem putant feugiat.</p>

<p>Sed iusto nihil populo an, ex pro novum homero cotidieque. Te utamur civibus eleifend qui, nam ei brute doming concludaturque, modo aliquam facilisi nec no. Vidisse maiestatis constituam eu his, esse pertinacia intellegam ius cu. Eos ei odio veniam, eu sumo altera adipisci eam, mea audiam prodesset persequeris ea. Ad vitae dictas vituperata sed, eum posse labore postulant id. Te eligendi principes dignissim sit, te vel dicant officiis repudiandae.</p>

<p>Id vel sensibus honestatis omittantur, vel cu nobis commune patrioque. In accusata definiebas qui, id tale malorum dolorem sed, solum clita phaedrum ne his. Eos mutat ullum forensibus ex, wisi perfecto urbanitas cu eam, no vis dicunt impetus. Assum novum in pri, vix an suavitate moderatius, id has reformidans referrentur. Elit inciderint omittantur duo ut, dicit democritum signiferumque eu est, ad suscipit delectus mandamus duo. An harum equidem maiestatis nec.</p>
At has veri feugait placerat, in semper offendit praesent his. Omnium impetus facilis sed at, ex viris tincidunt ius. Unum eirmod dignissim id quo. Sit te atomorum quaerendum neglegentur, his primis tamquam et. Eu quo quot veri alienum, ea eos nullam luptatum accusamus. Ea mel causae phaedrum reprimique, at vidisse dolores ocurreret nam.</blockquote>

<p>Existen m&uacute;ltiples variantes del texto original, algunas casi sin parecido con &eacute;l. Estas versiones incluyen letras adicionales que no son comunes en lat&iacute;n (como la&nbsp;<em>k</em>,&nbsp;<em>w</em>&nbsp;y&nbsp;<em>z</em>) o palabras sin sentido como&nbsp;<em>zzril</em>,&nbsp;<em>takimata</em>&nbsp;y&nbsp;<em>gubeergren</em>&nbsp;que intentan hacer la distribuci&oacute;n a&uacute;n m&aacute;s parecida al ingl&eacute;s.</p>

<p>Varios editores de texto proveen la funcionalidad de generaci&oacute;n de lorem ipsum.</p>

<h2><a id="temaq" name="temaq">V&eacute;ase tambi&eacute;n</a><span style="font-size:small"><span style="color:rgb(85, 85, 85)">[</span><a class="mw-editsection-visualeditor" href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;veaction=edit&amp;section=1" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Véase también">editar</a><span style="color:rgb(85, 85, 85)">&nbsp;&middot;&nbsp;</span><a href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;action=edit&amp;section=1" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Véase también">editar c&oacute;digo</a><span style="color:rgb(85, 85, 85)">]</span></span></h2>

<ul>
	<li><a href="http://es.wikipedia.org/wiki/Tipograf%C3%ADa" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Tipografía">Tipograf&iacute;a</a></li>
	<li><a href="http://es.wikipedia.org/wiki/Categor%C3%ADa:Frases_y_citas_latinas" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Categoría:Frases y citas latinas">Frases y citas latinas</a></li>
	<li><a href="http://es.wikipedia.org/wiki/Plantilla:Lorem_ipsum" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Plantilla:Lorem ipsum">Plantilla</a>&nbsp;para usar Lorem ipsum en art&iacute;culos de&nbsp;<a href="http://es.wikipedia.org/wiki/Wikipedia" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Wikipedia">Wikipedia</a></li>
</ul>

<h2>Enlaces externos<span style="font-size:small"><span style="color:rgb(85, 85, 85)">[</span><a class="mw-editsection-visualeditor" href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;veaction=edit&amp;section=2" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Enlaces externos">editar</a><span style="color:rgb(85, 85, 85)">&nbsp;&middot;&nbsp;</span><a href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;action=edit&amp;section=2" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Enlaces externos">editar c&oacute;digo</a><span style="color:rgb(85, 85, 85)">]</span></span></h2>

<ul>
	<li><img alt="" src="http://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/15px-Commons-logo.svg.png" style="border:none; height:20px; vertical-align:middle; width:15px" />&nbsp;<a href="http://es.wikipedia.org/wiki/Wikimedia_Commons" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Wikimedia Commons">Wikimedia Commons</a>&nbsp;alberga contenido multimedia sobre&nbsp;<strong><a class="extiw" href="http://commons.wikimedia.org/wiki/Lorem_ipsum" style="text-decoration: none; color: rgb(102, 51, 102); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="commons:Lorem ipsum">Lorem ipsum</a></strong>.</li>
	<li><a class="extiw" href="http://es.wikisource.org/wiki/en:Lorem_ipsum" style="text-decoration: none; color: rgb(102, 51, 102); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="s:en:Lorem ipsum">Texto tradicional en Wikisource</a></li>
</ul>

<h2>Referencias<span style="font-size:small"><span style="color:rgb(85, 85, 85)">[</span><a class="mw-editsection-visualeditor" href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;veaction=edit&amp;section=3" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Referencias">editar</a><span style="color:rgb(85, 85, 85)">&nbsp;&middot;&nbsp;</span><a href="http://es.wikipedia.org/w/index.php?title=Lorem_ipsum&amp;action=edit&amp;section=3" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;" title="Editar sección: Referencias">editar c&oacute;digo</a><span style="color:rgb(85, 85, 85)">]</span></span></h2>

<div class="listaref" style="font-size: 12px; margin-bottom: 0.5em; list-style-type: decimal;">
<ol style="list-style-type:inherit">
	<li><a href="http://es.wikipedia.org/wiki/Lorem_ipsum#cite_ref-1" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;">Jump up&uarr;</a>&nbsp;<a class="external text" href="http://www.straightdope.com/columns/read/2290/what-does-the-filler-text-lorem-ipsum-mean" rel="nofollow" style="text-decoration: none; color: rgb(102, 51, 102); background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAVklEQVR4Xn3PgQkAMQhDUXfqTu7kTtkpd5RA8AInfArtQ2iRXFWT2QedAfttj2FsPIOE1eCOlEuoWWjgzYaB/IkeGOrxXhqB+uA9Bfcm0lAZuh+YIeAD+cAqSz4kCMUAAAAASUVORK5CYII=); padding-right: 13px; background-position: 100% 50%; background-repeat: no-repeat no-repeat;">The Straightdope</a>, What does the filler text lorem-ipsum mean</li>
	<li><a href="http://es.wikipedia.org/wiki/Lorem_ipsum#cite_ref-2" style="text-decoration: none; color: rgb(11, 0, 128); background-image: none; background-position: initial initial; background-repeat: initial initial;">Jump up&uarr;</a>&nbsp;&laquo;A nadie le gusta el dolor para s&iacute; mismo, o lo busca y desea tenerlo, apenas porque es dolor...&raquo;</li>
</ol>
</div>
</div>
</div>

<div class="clear" style="padding: 0px; margin: 0px; clear: both; color: rgb(128, 128, 128); font-family: Verdana, Geneva, sans-serif; font-size: 12px; line-height: normal; background-color: rgb(254, 254, 253);">&nbsp;</div>
